# Generated by Django 5.2.4 on 2025-08-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='especialidad',
            new_name='Especialidad',
        ),
    ]
